openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
# Added by API Auto Mocking Plugin
  - description: Local
    url: localhost:8001/api

info:
  description: This is a simple API
  version: "1.0.0"
  title: Simple Inventory API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /signup:
    post:
      tags:
        - signup
      summary: signup
      operationId: signup
      description: |
        Sign Up
      requestBody:
        content:
          application/json:
            schema: 
              type: object
              $ref: '#/components/schemas/user'

          
      
      responses:
        '200':
          $ref: '#component/responses/signupSuccess'
        '500':
          $ref: '#component/responses/signupError'

  /signin:
    post:
      tags:
        - signin
      summary: signin
      operationId: signin
      description: |
        Sign In
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/user'

      responses:
        '200':
          $ref: '#component/responses/signinSuccess'
        '500':
          $ref: '#component/responses/signinError'

security:
  - name: []

components:
  schemas:
      User:
        type: object
        properties:
          id:
            type: string        
          email:
            type: string
            format: email
          password: 
            type: string
            minLength: 8
            format: password

  responses:

    signupSuccess:
        description: OK
        content:
          application/json:
            schema:
              type: string

    signupError:
      description: Error
      content:
        application/json:
          schema:
            type: string
    signinSuccess:
      description: OK
      content:
        application/json:
          schema:
            type: string

    signinError:
      description: Error
      content:
        application/json:
          schema:
            type: string

  
  securitySchemes:
    name:
      type: http
      scheme: bearer
      bearerFormat: JWT



    